version: '3.12.3'

services:
  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5433:5432"  # Открываем порт базы данных для соединений

  # Сервис для Python-приложения
  backend:
    build: ml_n_back
    container_name: python_app
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db  # Ожидаем, что база данных будет готова
    networks:
      - backend
    ports:
      - "8000:8000"  # Порт, на котором будет работать приложение
  frontend:
    build: ./frontend
    expose: [ 3000 ]
    restart: unless-stopped
    init: true
    env_file:
      - ./frontend/.env
    ports:
      - 443:443
      - 80:80
    volumes:
      - caddy_data:/data
      - caddy_config:/config

# Объем для данных базы данных
volumes:
  caddy_data:
  caddy_config:
  pgdata:
  static:

# Сети для изоляции
networks:
  backend:
    driver: bridge
